name: Akismet
version: "1.6.2"
description: Provides Akismet spam filter for form submissions
url: https://silentzconsulting.com/addons/akismet
developer: Erin Dalzell
developer_url: https://silentzconsulting.com/addons
commercial: true