fields:
  akismet_section:
    type: section
    display: Akismet
  akismet_key:
    type: text
    validate: required
  form_fields_section:
    type: section
    display: Form & Fields
  forms:
    type: grid
    display: ' '
    fields:
      form_and_fields:
        type: akismet
        display: 'Form & Fields'
        validate: required
    mode: table
    min_rows: "1"
    add_row: Add Form