fields:
  akismet_section:
    type: section
    display: Akismet
  akismet_key:
    type: text
    validate: required
  form_fields_section:
    type: section
    display: Form & Fields
  form_and_fields:
    type: akismet
    display: ' '